# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: CI flow

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build
      run: ./gradlew build -x test
      
    - name: Tests
      run: ./gradlew test

    - name: Package
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: Artifact
        path: build/libs/*.jar
        retention-days: 5

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Test Results
        path: build/reports/
        retention-days: 5


#     # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
#     # the publishing section of your build.gradle
#     - name: Publish to GitHub Packages
#       run: gradle publish
#       env:
#         USERNAME: ${{ github.actor }}
#         TOKEN: ${{ secrets.GITHUB_TOKEN }}
